### ISSUE TITLE
Failed to build on TravisCI with Crystal 0.27.1

### ISSUE THREAD

**Issue by anykeyh** [veelenga/ameba#88] opened 2019-02-04 08:53 UTC
Hello,

I've an issue with my build here: https://travis-ci.org/anykeyh/clear/jobs/488396058

```
Failed make bin:
/usr/bin/shards build 
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
Unhandled exception: Overflow (OverflowError)
Failed to raise an exception: END_OF_STACK
[0x2b57a994fa76] ???
[0x2b57a8ea3a09] ???
[0x2b57a8eb71c2] ???
[0x2b57a8eade78] ???
[0x2b57a8eaa824] ???
[0x2b57a8ee2542] ???
[0x2b57a8ea6ced] ???
[0x2b57aad8cf5e] ???
```

I'm using crystal v0.27.1 and ameba v0.9

```
$ crystal --version
Crystal 0.27.1 [64137d045] (2019-01-30)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
Any ideas? It works well on my dev machine. It might be related to LLVM since I'm using the 6.0 on my dev machine vs 4.0 on the travis build.

**Comment by veelenga** [comment] 2019-02-04 11:51
@anykeyh looking. Can't reproduce it either.

**Comment by veelenga** [comment] 2019-02-04 12:46
Relates to:

- https://github.com/crystal-lang/crystal/issues/7369
- https://github.com/crystal-lang/crystal/issues/7368

**Comment by anykeyh** [comment] 2019-02-04 12:48
It's weird. I wonder if any other shards building ameba binary in Travis-CI experience the same problem? 
Any work-around possible?

**Comment by veelenga** [comment] 2019-02-04 13:19
@anykeyh 

* You can temporary switch to `osx` operation system on Travis

```yml
# .travis.yml
os: osx
```

**or**

* use this branch as a temporary workaround:

```yml
development_dependencies:
  ameba:
    github: veelenga/ameba
    branch: crystal-0.27.1-workaround

```

**Comment by anykeyh** [comment] 2019-02-04 13:52
It's good, I'll use the branch work-around until Crystal is fixed.

**Comment by gdotdesign** [comment] 2019-02-04 15:00
I had the same issue (on Travis) and the workaround fixed it for me :+1:

**Comment by anykeyh** [comment] 2019-02-04 15:22
FYI: The branch fix is not working:

https://travis-ci.org/anykeyh/clear/builds/488509098

**Comment by veelenga** [comment] 2019-02-06 07:57
Closing this now. Will not remove the workaround branch in case anyone uses it.

**Closed by veelenga** 2019-02-06 07:57 UTC
