### ISSUE TITLE
Crystal 0.29 compatibility

### ISSUE THREAD

**Issue by carlhoerberg** [veelenga/ameba#107] opened 2019-06-06 13:52 UTC
```
Installing ameba (0.9.2)
Postinstall make bin
Failed make bin:
/usr/bin/shards build 
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
Error in src/cli.cr:1: while requiring "./ameba/cli/cmd"
require "./ameba/cli/cmd"
^
in src/ameba/cli/cmd.cr:1: while requiring "../../ameba"
require "../../ameba"
^
in src/ameba.cr:1: while requiring "./ameba/*"
require "./ameba/*"
^
Syntax error in src/ameba/inline_comments.cr:97: unexpected token: =
      commented? = false
      ^
Makefile:8: recipe for target 'bin/ameba' failed
make: *** [bin/ameba] Error 1
```

related to https://github.com/crystal-lang/crystal/pull/7582 ?

**Comment by Sija** [comment] 2019-06-06 14:27
Duplicate of #106

**Closed** 2019-06-06 16:10 UTC

**Comment by veelenga** [comment] 2019-06-06 16:15
@carlhoerberg the compatible release has been just published: https://github.com/veelenga/ameba/releases/tag/v0.10.0
